#!/bin/bash

### BEGIN INIT INFO
# Provides:          amazon-echo-bridge
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:
# Required-Stop:
# Short-Description: Amazon Echo Bridge for Vera
# Description:       A simple init script for the RaspberryPi
#                    to launch the Amazon-Echo-Bridge Jar.
# Special-Thanks:	 armzilla
### END INIT INFO

VER="0.2.1"
IP=`ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`

# What is this?
DESC="Amazon Echo Bridge"

cd /opt/echo
nohup java -jar amazon-echo-bridge-$VER.jar –-upnp.config.address=$IP > /dev/null 2>&1 &